Repository softeng2223-inf-uniba/progetto2223-dijkstra, pull requests merged in 2023-04, with the labels that each got.

#3 applicata la patch "fix_guida_studente_1.patch"
  docs/Guida per lo studente.md
Labels: bug, documentation

#4 applicata la patch "fix_guida_studente_2.patch"
  docs/Guida per lo studente.md
Labels: bug, documentation

#6 aggiunto il Badge di GitHub Actions nel file README.md
  README.md
Labels: documentation

#10 creato e modificato file ISPIRATORE.md
  docs/ISPIRATORE.md
Labels: documentation, enhancement

#13 aggiornata cartella ./docs/img
  docs/Guida per lo studente.md
  docs/img/CoverallsBadge_1.png
  docs/img/CoverallsBadge_2.png
  docs/img/ExecuteDockerImage_1.png
  docs/img/ExecuteDockerImage_2.png
  docs/img/Import_e_Java_-_Eclipse.png
  docs/img/SaveTokenInSecret_1.png
  docs/img/SaveTokenInSecret_2.png
  docs/img/SaveTokenInSecret_3.png
  docs/img/SaveTokenInSecret_4.png
  docs/img/SaveTokenInSecret_5.png
  docs/img/SaveTokenInSecret_6.png
  docs/img/SaveTokenInSecret_7.png
  docs/img/Update_GitHub_badge_1.png
  docs/img/Update_GitHub_badge_2.png
  docs/img/Update_GitHub_badge_3.png
  docs/img/Update_GitHub_badge_4.png
  docs/img/actions+coveralls-badges.png
  docs/img/actions-badge.png
  docs/img/add_repo_coveralls.png
  docs/img/cloneusingurl.png
  docs/img/javadoc_location.png
  docs/img/joinTeam.png
  docs/img/manageAccess.png
  docs/img/packageSettings.png
  docs/img/project-properties.png
  docs/img/project_properties.png
  docs/img/readyToGo.png
  docs/img/run_gradle_check.png
Labels: documentation, enhancement

#14 aggiunto PMD come strumento di Quality Assurance
  docs/Guida per lo studente.md
Labels: documentation

#15 creato il file CODE_OF_CONDUCT.md
  docs/CODE_OF_CONDUCT.md
Labels: documentation, enhancement

#17 aggiornata la struttura della repository nel file README.md
  README.md
Labels: bug, documentation
